import { auth, db } from "./firebase.js";
import { signInWithEmailAndPassword,onAuthStateChanged,signOut } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js";
import { collection,getDocs,query,where,addDoc,updateDoc,deleteDoc,doc,getDoc,serverTimestamp,limit } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const arr=v=>Array.isArray(v)?v:(v?[v]:[]); const branches={scientific:"العلمي",literary:"الأدبي",industrial:"الصناعي"};
let role=null, subjects=[], resources=[], foundations=[], suggestions=[], admins=[], editing=null;
const can=r=>({superadmin:3,content_admin:2,reviewer:1}[r]||0)>=({superadmin:3,content_admin:2,reviewer:1}[role]||0);
function msg(el,t,e=false){if(el){el.textContent=t;el.className=e?"message error":"message success";}}
function branchesHTML(ids=[]){return arr(ids).map(x=>branches[x]||x).join("، ")||"غير محدد";}
async function loadRole(user){const snap=await getDoc(doc(db,"admins",user.uid)); if(!snap.exists()||snap.data().active!==true) throw new Error("NO_ADMIN"); return snap.data().role||"reviewer";}
async function all(col){const s=await getDocs(collection(db,col));return s.docs.map(d=>({id:d.id,...d.data()}));}
async function refresh(){[subjects,resources,foundations,suggestions]=await Promise.all([all("subjects"),all("resources"),all("foundations"),getDocs(query(collection(db,"suggestions"),where("status","==","pending"),limit(300))).then(s=>s.docs.map(d=>({id:d.id,...d.data()})))]); if(role==='superadmin'){admins=await all('admins');} $("#subjectsCount").textContent=subjects.length;$("#resourcesCount").textContent=resources.length;$("#foundationsCount").textContent=foundations.length;$("#suggestionsCount").textContent=suggestions.length;renderAll();}
function subjectOptions(branch=""){return subjects.filter(s=>!branch||arr(s.branchIds).includes(branch)).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");}
function renderAll(){
 $("#subjectsList").innerHTML=subjects.sort((a,b)=>(a.order??9999)-(b.order??9999)).map(s=>`<div class="admin-item"><div><strong>${esc(s.name)}</strong><p>${branchesHTML(s.branchIds)} · ترتيب ${s.order??"-"}</p></div><div><button class="btn small" data-edit-sub="${s.id}">تعديل</button><button class="btn danger small" data-del-sub="${s.id}">حذف</button></div></div>`).join("")||'<div class="empty">لا توجد مواد.</div>';
 $("#resourcesList").innerHTML=resources.sort((a,b)=>(a.order??9999)-(b.order??9999)).map(r=>`<div class="admin-item"><div><strong>${esc(r.title)}</strong><p>${branches[r.branchId]||branchesHTML(r.branchIds)} · ${esc(r.type||"مصدر")} · <a href="${esc(r.url)}" target="_blank" rel="noopener">الرابط</a></p></div><div><button class="btn small" data-edit-res="${r.id}">تعديل</button><button class="btn danger small" data-del-res="${r.id}">حذف</button></div></div>`).join("")||'<div class="empty">لا توجد مصادر.</div>';
 $("#foundationsList").innerHTML=foundations.sort((a,b)=>(a.order??9999)-(b.order??9999)).map(r=>`<div class="admin-item"><div><strong>🧠 ${esc(r.title)}</strong><p>${branchesHTML(r.branchIds)} · ${esc(r.level||"")} · ${esc(r.type||"")}</p></div><div><button class="btn small" data-edit-found="${r.id}">تعديل</button><button class="btn danger small" data-del-found="${r.id}">حذف</button></div></div>`).join("")||'<div class="empty">لا يوجد تأسيس.</div>';
 $("#suggestionsList").innerHTML=suggestions.map(s=>`<div class="admin-item suggestion"><div><strong>${esc(s.title)}</strong><p>${s.contentType==='foundation'?'🧠 تأسيس':'📚 مصدر'} · ${branchesHTML(s.branchIds)} · الطالب: ${esc(s.studentName||"غير محدد")}</p><p>${esc(s.description||"")}</p><a href="${esc(s.url)}" target="_blank" rel="noopener">فتح الرابط</a></div><div><button class="btn primary small" data-approve="${s.id}">✅ موافقة</button><button class="btn danger small" data-reject="${s.id}">❌ رفض</button></div></div>`).join("")||'<div class="empty">لا توجد اقتراحات معلقة.</div>';
 $("#recentSuggestions").innerHTML=suggestions.slice(0,5).map(s=>`<div class="admin-item"><div><strong>${esc(s.title)}</strong><p>قيد المراجعة · ${esc(s.studentName||"طالب")}</p></div><button class="btn small" data-tabjump="suggestions">مراجعة</button></div>`).join("")||'<div class="empty">لا توجد اقتراحات معلقة.</div>';
 $$(".super-only").forEach(x=>x.classList.toggle("hidden",role!=="superadmin")); if($('#adminsList')) $('#adminsList').innerHTML=role==='superadmin' ? (admins.map(a=>`<div class="admin-item"><div><strong>${esc(a.email||a.id)}</strong><p>${esc(a.role||'reviewer')} · ${a.active?'نشط':'موقوف'} · UID: ${esc(a.id)}</p></div><button class="btn danger small" data-del-admin="${a.id}">تعطيل</button></div>`).join('')||'<div class="empty">لا يوجد أدمن.</div>') : '';
}
function openTab(name){$$('.admin-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.admin-panel').forEach(p=>p.classList.add('hidden'));$("#"+name+"Panel")?.classList.remove('hidden');}
$$('.admin-tab').forEach(b=>b.onclick=()=>{if(b.classList.contains('hidden'))return;openTab(b.dataset.tab)});
document.addEventListener('click',async e=>{const t=e.target;if(t.dataset.tabjump)openTab(t.dataset.tabjump); if(t.dataset.delSub&&confirm('حذف المادة؟'))await deleteDoc(doc(db,'subjects',t.dataset.delSub)); if(t.dataset.delRes&&confirm('حذف المصدر؟'))await deleteDoc(doc(db,'resources',t.dataset.delRes)); if(t.dataset.delFound&&confirm('حذف التأسيس؟'))await deleteDoc(doc(db,'foundations',t.dataset.delFound)); if(t.dataset.approve)await review(t.dataset.approve,true); if(t.dataset.reject)await review(t.dataset.reject,false); if(t.dataset.editSub)editSubject(t.dataset.editSub);if(t.dataset.editRes)editResource(t.dataset.editRes);if(t.dataset.editFound)editFoundation(t.dataset.editFound); if(t.dataset.delAdmin&&confirm('تعطيل هذا الأدمن؟')){await updateDoc(doc(db,'admins',t.dataset.delAdmin),{active:false,updatedAt:serverTimestamp()});await refresh();} if(t.id==='addSubjectBtn'){editing=null;$('#subjectForm').classList.remove('hidden')} if(t.id==='cancelSubject')$('#subjectForm').classList.add('hidden');if(t.id==='addResourceBtn'){editing=null;$('#resourceForm').classList.remove('hidden')}if(t.id==='cancelResource')$('#resourceForm').classList.add('hidden');if(t.id==='addFoundationBtn'){editing=null;$('#foundationForm').classList.remove('hidden')}if(t.id==='cancelFoundation')$('#foundationForm').classList.add('hidden');});
async function review(id,approve){const s=suggestions.find(x=>x.id===id);if(!s)return;const data={...s};delete data.id;delete data.status;delete data.createdAt;if(approve){data.createdAt=serverTimestamp();data.updatedAt=serverTimestamp();if(s.contentType==='foundation')await addDoc(collection(db,'foundations'),data);else await addDoc(collection(db,'resources'),data);}await updateDoc(doc(db,'suggestions',id),{status:approve?'approved':'rejected',reviewedAt:serverTimestamp(),reviewedBy:auth.currentUser.uid});await refresh();}
function editSubject(id){editing=id;const s=subjects.find(x=>x.id===id);$('#subjectName').value=s.name||'';$('#subjectOrder').value=s.order??'';$('#subjectDescription').value=s.description||'';$$('#subjectForm input[type=checkbox]').forEach(c=>c.checked=arr(s.branchIds).includes(c.value));$('#subjectForm').classList.remove('hidden');openTab('subjects');}
function editResource(id){editing=id;const r=resources.find(x=>x.id===id);$('#resourceTitle').value=r.title||'';$('#resourceUrl').value=r.url||'';$('#resourceBranch').value=r.branchId||arr(r.branchIds)[0]||'';$('#resourceSubject').innerHTML=subjectOptions($('#resourceBranch').value);$('#resourceSubject').value=r.subjectId||'';$('#resourceType').value=r.type||'';$('#resourceCategory').value=r.category||r.categoryId||'';$('#resourceKeywords').value=arr(r.keywords).join(', ');$('#resourceOrder').value=r.order??'';$('#resourceDescription').value=r.description||'';$('#resourceForm').classList.remove('hidden');openTab('resources');}
function editFoundation(id){editing=id;const r=foundations.find(x=>x.id===id);$('#foundationTitle').value=r.title||'';$('#foundationUrl').value=r.url||'';$('#foundationBranch').value=arr(r.branchIds)[0]||'';$('#foundationSubject').innerHTML=subjectOptions($('#foundationBranch').value);$('#foundationSubject').value=r.subjectId||'';$('#foundationLevel').value=r.level||'beginner';$('#foundationType').value=r.type||'lesson';$('#foundationKeywords').value=arr(r.keywords).join(', ');$('#foundationOrder').value=r.order??'';$('#foundationDescription').value=r.description||'';$('#foundationForm').classList.remove('hidden');openTab('foundations');}
function parseJSON(id,msgid){try{return JSON.parse($(id).value)}catch{msg($(msgid),'JSON غير صالح.',true);return null}}
$('#loginBtn').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value)}catch{msg($('#loginMsg'),'فشل تسجيل الدخول أو الحساب ليس ضمن admins.',true)}};$('#password').onkeydown=e=>{if(e.key==='Enter')$('#loginBtn').click()};$('#logoutBtn').onclick=()=>signOut(auth);
$('#resourceBranch').onchange=()=>$('#resourceSubject').innerHTML='<option value="">اختر المادة</option>'+subjectOptions($('#resourceBranch').value);$('#foundationBranch').onchange=()=>$('#foundationSubject').innerHTML='<option value="">اختر المادة</option>'+subjectOptions($('#foundationBranch').value);
$('#subjectForm').onsubmit=async e=>{e.preventDefault();if(!can('content_admin'))return;const data={name:$('#subjectName').value.trim(),branchIds:$$('#subjectForm input[type=checkbox]:checked').map(x=>x.value),description:$('#subjectDescription').value.trim(),order:Number($('#subjectOrder').value)||9999,updatedAt:serverTimestamp()};if(!data.branchIds.length)return msg($('#subjectMsg'),'اختر فرعًا واحدًا على الأقل.',true);if(editing)await updateDoc(doc(db,'subjects',editing),data);else await addDoc(collection(db,'subjects'),{...data,createdAt:serverTimestamp()});editing=null;$('#subjectForm').classList.add('hidden');await refresh();};
$('#resourceForm').onsubmit=async e=>{e.preventDefault();const url=$('#resourceUrl').value.trim();try{new URL(url)}catch{return msg($('#resourceMsg'),'الرابط غير صالح.',true)}const dup=resources.some(r=>r.url===url&&r.id!==editing);if(dup)return msg($('#resourceMsg'),'هذا الرابط موجود بالفعل.',true);const data={title:$('#resourceTitle').value.trim(),url,branchId:$('#resourceBranch').value,subjectId:$('#resourceSubject').value,type:$('#resourceType').value.trim(),category:$('#resourceCategory').value.trim(),keywords:$('#resourceKeywords').value.split(',').map(x=>x.trim()).filter(Boolean),order:Number($('#resourceOrder').value)||9999,description:$('#resourceDescription').value.trim(),updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(db,'resources',editing),data);else await addDoc(collection(db,'resources'),{...data,createdAt:serverTimestamp()});editing=null;$('#resourceForm').classList.add('hidden');await refresh();};
$('#foundationForm').onsubmit=async e=>{e.preventDefault();const url=$('#foundationUrl').value.trim();try{new URL(url)}catch{return msg($('#foundationMsg'),'الرابط غير صالح.',true)}const dup=foundations.some(r=>r.url===url&&r.id!==editing);if(dup)return msg($('#foundationMsg'),'هذا الرابط موجود بالفعل.',true);const data={title:$('#foundationTitle').value.trim(),url,branchIds:[$('#foundationBranch').value],subjectId:$('#foundationSubject').value,level:$('#foundationLevel').value,type:$('#foundationType').value,keywords:$('#foundationKeywords').value.split(',').map(x=>x.trim()).filter(Boolean),order:Number($('#foundationOrder').value)||9999,description:$('#foundationDescription').value.trim(),updatedAt:serverTimestamp()};if(editing)await updateDoc(doc(db,'foundations',editing),data);else await addDoc(collection(db,'foundations'),{...data,createdAt:serverTimestamp()});editing=null;$('#foundationForm').classList.add('hidden');await refresh();};
async function importItems(text,col,msgid,type){const list=parseJSON(text,msgid);if(!Array.isArray(list))return;const urls=new Set(resources.concat(foundations).map(x=>x.url));let added=0,skip=0;for(const x of list){if(!x.title||!x.url||urls.has(x.url)){skip++;continue}try{new URL(x.url)}catch{skip++;continue}if(type==='resource'&&!x.subjectId){skip++;continue}if(type==='foundation'&&!x.subjectId){skip++;continue}await addDoc(collection(db,col),{...x,branchId:x.branchId||arr(x.branchIds)[0]||'',branchIds:x.branchIds||arr(x.branchId),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});urls.add(x.url);added++;}msg($(msgid),`تمت إضافة ${added} وتجاهل ${skip} مكرر/غير صالح.`);await refresh();}
$('#importResources').onclick=()=>importItems('#bulkResources','resources','#bulkResourceMsg','resource');$('#importFoundations').onclick=()=>importItems('#bulkFoundations','foundations','#bulkFoundationMsg','foundation');
onAuthStateChanged(auth,async user=>{if(!user){$('#loginSection').classList.remove('hidden');$('#dashboard').classList.add('hidden');return}try{role=await loadRole(user);$('#loginSection').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#adminEmail').textContent=user.email||user.uid;$('#roleBadge').textContent=role;await refresh();}catch(e){await signOut(auth);msg($('#loginMsg'),'هذا الحساب ليس لديه صلاحية أدمن.',true)}});

$('#addAdminBtn')?.addEventListener('click',()=>$('#adminForm').classList.remove('hidden')); $('#cancelAdmin')?.addEventListener('click',()=>$('#adminForm').classList.add('hidden')); $('#adminForm')?.addEventListener('submit',async e=>{e.preventDefault();if(role!=='superadmin')return msg($('#adminMsg'),'هذه العملية لـ Super Admin فقط.',true);const uid=$('#adminUid').value.trim();if(!uid)return;await updateDoc(doc(db,'admins',uid),{role:$('#adminRole').value,active:$('#adminActive').checked,updatedAt:serverTimestamp()}).catch(async()=>{await (await import('https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js')).setDoc(doc(db,'admins',uid),{role:$('#adminRole').value,active:$('#adminActive').checked,createdAt:serverTimestamp()});});$('#adminForm').classList.add('hidden');await refresh();});
