import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const required=['index.html','firebase.json','firestore.rules','firestore.indexes.json','README.md','tests.html','my-tests.html','shared-tests.html','css/variables.css','js/services/firebase.js','js/services/firebase/auth.js','js/services/firebase/adminCore.js','js/services/firebase/permissions.js','js/repositories/resourceRepository.js','js/repositories/solutionRepository.js','js/repositories/foundationRepository.js','js/repositories/testRepository.js','js/repositories/studentTestRepository.js','js/services/ai/aiService.js','worker/src/index.js','worker/wrangler.toml','admin/index.html','admin/problem-reports.html','admin/suggestions.html','admin/directorates.html','admin/schools.html','admin/templates.html','admin/tests.html','js/admin/tests.js','js/admin/templates.js','js/pages/tests.js','js/pages/my-tests-v2.js','js/pages/shared-tests.js'];
const htmlFiles=[],jsFiles=[],failures=[];
function walk(dir,matcher,output){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(['.git','node_modules'].includes(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full,matcher,output);else if(matcher(entry.name))output.push(full)}}
function cleanTarget(value){return value.split('#')[0].split('?')[0]}
function checkTarget(file,raw,kind){const target=cleanTarget(raw);if(!target||target.startsWith('#')||/^(https?:|mailto:|tel:|javascript:|data:)/i.test(target))return;const resolved=target.startsWith('/')?path.join(root,target.slice(1)):path.resolve(path.dirname(file),target);if(!fs.existsSync(resolved))failures.push(`${kind} missing: ${path.relative(root,file)} -> ${raw}`)}
walk(root,name=>name.endsWith('.html'),htmlFiles);walk(root,name=>/\.m?js$/.test(name),jsFiles);
const missing=required.filter(p=>!fs.existsSync(path.join(root,p)));
for(const file of htmlFiles){const source=fs.readFileSync(file,'utf8');if(/<script[^>]+(?:src|type)=["'][^"']*(?:\.ts|tsx|react|vue)/i.test(source))failures.push(`Forbidden frontend reference: ${path.relative(root,file)}`);for(const match of source.matchAll(/(?:href|src)=["']([^"']+)["']/gi))checkTarget(file,match[1],'HTML target')}
for(const file of jsFiles){const source=fs.readFileSync(file,'utf8');for(const match of source.matchAll(/(?:from\s*["']|import\s*\(["'])(\.\.?\/[^"']+)["']/g)){let target=match[1];if(!path.extname(target))target+='.js';if(!fs.existsSync(path.resolve(path.dirname(file),target)))failures.push(`JS import missing: ${path.relative(root,file)} -> ${match[1]}`)}if(/firebasejs\/11\./.test(source))failures.push(`Legacy Firebase SDK v11 reference: ${path.relative(root,file)}`);if(/services\/firebase\/firebaseConfig\.js/.test(source))failures.push(`Legacy Firebase config import: ${path.relative(root,file)}`)}
try{const indexes=JSON.parse(fs.readFileSync(path.join(root,'firestore.indexes.json'),'utf8'));if(!Array.isArray(indexes.indexes))failures.push('firestore.indexes.json: indexes must be an array');const collections=new Set((indexes.indexes||[]).map(index=>index.collectionGroup));for(const collection of ['resources','flashcards','solutions','suggestions','problemReports'])if(!collections.has(collection))failures.push(`Missing Firestore index coverage: ${collection}`)}catch(error){failures.push(`firestore.indexes.json invalid: ${error.message}`)}
try{const rules=fs.readFileSync(path.join(root,'firestore.rules'),'utf8');for(const role of ['reviewer','content_admin','super_admin'])if(!rules.includes(`'${role}'`))failures.push(`Firestore role missing from rules: ${role}`);if(!rules.includes('canonicalRole()'))failures.push('Firestore admin writes are missing canonical role validation');if(!rules.includes('lastLoginAt'))failures.push('Student profiles are missing lastLoginAt security coverage');if(!/match \/users\/\{uid\}[\s\S]*allow list: if superAdmin\(\);/.test(rules))failures.push('Student registry is not protected by superAdmin list access');for(const match of ['match /directorates/{id}','match /schools/{id}','match /tests/{id}','match /studentTests/{testId}','match /studentTestShares/{shareId}'])if(!rules.includes(match))failures.push(`Firestore rule missing: ${match}`);if(!rules.includes('questions.size() <= 50'))failures.push('Student tests are missing the 50-question security limit');if(!rules.includes("resource.data.status == 'approved' && request.resource.data.status == 'published' && contentAdmin()"))failures.push('Source registry publish transition is not protected by contentAdmin') }catch(error){failures.push(`firestore.rules unreadable: ${error.message}`)}
try{const constants=fs.readFileSync(path.join(root,'js/core/constants.js'),'utf8');const adminData=fs.readFileSync(path.join(root,'js/admin/data.js'),'utf8');if(!/ROLES\s*=/.test(constants)||!/REVIEWER/.test(constants)||!/CONTENT_ADMIN/.test(constants)||!/SUPER_ADMIN/.test(constants))failures.push('Canonical role constants are incomplete');if(!/ROLES\.SUPER_ADMIN/.test(adminData)||!/ROLES\.CONTENT_ADMIN/.test(adminData))failures.push('Admin data config is not using canonical role constants')}catch(error){failures.push(`Role configuration unreadable: ${error.message}`)}
const adminIndex=fs.readFileSync(path.join(root,'admin/index.html'),'utf8');if(!/src=["']\.\.\/js\/admin\/index\.js["']/.test(adminIndex))failures.push('Admin entrypoint does not use js/admin/index.js');for(const orphan of ['admin/dashboard.html','js/admin/dashboard.js','js/admin/fixes.js','js/admin/form-enhancements.js'])if(fs.existsSync(path.join(root,orphan)))failures.push(`Obsolete admin file still exists: ${orphan}`);
const adminSources=jsFiles.filter(f=>f.includes(`${path.sep}admin${path.sep}`)).map(f=>fs.readFileSync(f,'utf8')).join('\n');if(/getDocs\(collection\(db/.test(adminSources))failures.push('Admin code contains unbounded getDocs(collection(db,...))');if(/localStorage\.(getItem|setItem).*?(gemini|drive)|localStorage\.(getItem|setItem).*api[_-]?key/i.test(adminSources))failures.push('Admin code stores Gemini/Drive API keys in localStorage');if(/MutationObserver/.test(adminSources))failures.push('Admin code contains MutationObserver DOM hacks');if(/setInterval/.test(adminSources))failures.push('Admin code contains setInterval polling');
if(missing.length||failures.length){console.error('Smoke test failed');if(missing.length)console.error('Missing required files:',missing);for(const failure of failures)console.error(failure);process.exit(1)}console.log(`Smoke test passed: ${htmlFiles.length} HTML pages and ${jsFiles.length} JS modules checked.`);
