import { db } from '../services/firebase.js';
import { collection, doc, getDocs, limit, query, where, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { getAdmin } from './data.js';
import { logAction } from './audit.js';

const PAGE_BATCH=400;
const collectionNames={resources:'المصادر',foundations:'التأسيس',flashcards:'البطاقات',solutions:'الحلول'};
const schemas={
  resources:{required:['title','url','subjectId'],array:['branchIds','keywords','tags'],max:{title:200,description:5000},url:true},
  foundations:{required:['title','url','subjectId'],array:['branchIds','keywords'],max:{title:200,description:5000},url:true},
  flashcards:{required:['question','answer'],array:[],max:{question:5000,answer:10000,explanation:10000}},
  solutions:{required:['title'],array:['keywords'],max:{title:200,problem:10000,solution:20000,steps:20000,notes:5000}}
};
const normalizeUrl=value=>{const raw=String(value??'').trim();if(!raw)return '';try{const u=new URL(raw);u.protocol=u.protocol.toLowerCase();u.hostname=u.hostname.toLowerCase();if((u.protocol==='https:'&&u.port==='443')||(u.protocol==='http:'&&u.port==='80'))u.port='';if(u.pathname.length>1)u.pathname=u.pathname.replace(/\/+$/,'');u.hash='';return u.toString()}catch{return ''}};
function normalizeRow(item){const out={};for(const[k,v]of Object.entries(item||{})){if(k==='createdAt'||k==='updatedAt')continue;if(Array.isArray(v))out[k]=[...new Set(v.map(x=>String(x).trim()).filter(Boolean))].slice(0,100);else if(typeof v==='string')out[k]=v.trim();else out[k]=v}if(out.url)out.url=normalizeUrl(out.url);return out}
function validateRow(collectionName,item,index,seen){const schema=schemas[collectionName],row=normalizeRow(item),errors=[];if(!item||typeof item!=='object'||Array.isArray(item))return{row:null,error:`${index+1}: يجب أن يكون العنصر كائنًا.`};for(const key of schema.required)if(!String(row[key]??'').trim()&&(key!=='url'||!row.url))errors.push(`${index+1}: الحقل ${key} مطلوب.`);for(const key of schema.array)if(row[key]!==undefined&&!Array.isArray(row[key]))errors.push(`${index+1}: الحقل ${key} يجب أن يكون مصفوفة.`);for(const[key,max]of Object.entries(schema.max))if(String(row[key]??'').length>max)errors.push(`${index+1}: الحقل ${key} يتجاوز ${max} حرفًا.`);if(schema.url){const normalized=normalizeUrl(row.url);if(!normalized)errors.push(`${index+1}: الرابط غير صالح.`);else if(seen.has(normalized))errors.push(`${index+1}: الرابط مكرر داخل الملف.`);else{seen.add(normalized);row.url=normalized}}if(collectionName==='resources'&&!row.branchIds?.length)errors.push(`${index+1}: يجب تحديد فرع واحد على الأقل.`);return{row,error:errors.join(' ')} }
async function findExistingUrls(urls){const existing=new Set();const values=[...new Set(urls.filter(Boolean))];for(let i=0;i<values.length;i+=30){const chunk=values.slice(i,i+30);const snap=await getDocs(query(collection(db,'resources'),where('url','in',chunk),limit(30)));snap.docs.forEach(d=>{const u=normalizeUrl(d.data()?.url);if(u)existing.add(u)})}return existing}
async function findExistingFoundationUrls(urls){const existing=new Set();const values=[...new Set(urls.filter(Boolean))];for(let i=0;i<values.length;i+=30){const chunk=values.slice(i,i+30);const snap=await getDocs(query(collection(db,'foundations'),where('url','in',chunk),limit(30)));snap.docs.forEach(d=>{const u=normalizeUrl(d.data()?.url);if(u)existing.add(u)})}return existing}
export function renderBulk(root){root.innerHTML=`<div class="section-head"><div><h2>استيراد جماعي</h2><p class="muted">تحقق من schema والروابط والتكرار قبل الكتابة إلى Firestore.</p></div></div><div class="form-card"><label>القسم<select id="bulkCollection"><option value="resources">المصادر</option><option value="foundations">التأسيس</option><option value="flashcards">البطاقات</option><option value="solutions">الحلول</option></select></label><label>بيانات JSON<textarea id="bulkJson" rows="14" placeholder='[{"title":"...","url":"https://..."}]'></textarea></label><div class="actions"><button id="previewBulk" class="button">معاينة وفحص</button><button id="runBulk" class="button primary" disabled>تنفيذ الاستيراد</button></div><pre id="bulkPreview" class="bulk-preview"></pre></div>`;let valid=[];
  document.getElementById('previewBulk').onclick=async()=>{const preview=document.getElementById('bulkPreview'),run=document.getElementById('runBulk');run.disabled=true;valid=[];try{const raw=JSON.parse(document.getElementById('bulkJson').value);const rows=Array.isArray(raw)?raw:(raw?.items||raw?.resources||raw?.foundations||raw?.flashcards||raw?.solutions||[]);if(!Array.isArray(rows)||!rows.length)throw Error('لم يتم العثور على عناصر للاستيراد.');const c=document.getElementById('bulkCollection').value,seen=new Set(),errors=[];for(let i=0;i<rows.length;i++){const result=validateRow(c,rows[i],i,seen);if(result.error)errors.push(result.error);else valid.push(result.row)}if(c==='resources'||c==='foundations'){const existing=c==='resources'?await findExistingUrls(valid.map(x=>x.url)):await findExistingFoundationUrls(valid.map(x=>x.url));valid=valid.filter((row,i)=>{if(existing.has(row.url)){errors.push(`عنصر ${i+1}: الرابط موجود مسبقًا في Firestore.`);return false}return true})}preview.textContent=`القسم: ${collectionNames[c]}\nصالح: ${valid.length}\nمرفوض: ${errors.length}\n\n${errors.slice(0,50).join('\n')}`;run.disabled=!valid.length}catch(e){preview.textContent=`فشل الفحص: ${e.message}`;run.disabled=true}};
  document.getElementById('runBulk').onclick=async()=>{const c=document.getElementById('bulkCollection').value,button=document.getElementById('runBulk'),preview=document.getElementById('bulkPreview'),admin=getAdmin();if(!admin){preview.textContent+='\n\nانتهت جلسة الإدارة.';return}button.disabled=true;let imported=0;try{for(let i=0;i<valid.length;i+=PAGE_BATCH){const batch=writeBatch(db);valid.slice(i,i+PAGE_BATCH).forEach(item=>{const ref=doc(collection(db,c));batch.set(ref,{...item,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})});await batch.commit();imported+=Math.min(PAGE_BATCH,valid.length-i);preview.textContent+=`\nتمت دفعة ${imported} / ${valid.length}.`}await logAction(admin,'bulk_import',c,'bulk',`imported ${imported}`);preview.textContent+=`\n\nاكتمل الاستيراد: ${imported} من ${collectionNames[c]}.`}catch(e){console.error('[admin.bulk]',e);preview.textContent+=`\n\nتوقف الاستيراد بعد ${imported} عنصرًا. الدفعات السابقة محفوظة، ويمكن إعادة المعاينة للمتبقي.`}finally{button.disabled=false}};
}
