import { requireAdmin, ROLES } from '../services/firebase/adminCore.js';
import { configs, loadPage, saveAdminItem, removeAdminItem, state } from './data.js';
const params=new URLSearchParams(location.search);const collectionName=params.get('collection')||'branches';const label=configs[collectionName]?.label;if(!['branches','subjects','categories'].includes(collectionName)||!label)throw new Error('UNSUPPORTED_ADMIN_COLLECTION');const $=id=>document.getElementById(id);let editingId=null,rows=[];
function stateMessage(text,error=false){const el=document.createElement('div');el.className=error?'message error':'message';el.textContent=text;el.setAttribute('role',error?'alert':'status');return el}
function render(){const root=$('content-list');root.replaceChildren();if(!rows.length){root.append(stateMessage('لا توجد بيانات.'));return}rows.forEach(item=>{const row=document.createElement('article');row.className='card admin-row';const info=document.createElement('div');const h=document.createElement('h3');h.textContent=item.name||'بدون اسم';const p=document.createElement('p');p.textContent=`${item.active===false?'معطّل':'مفعّل'} • الترتيب ${Number(item.order)||0}`;info.append(h,p);const actions=document.createElement('div');actions.className='actions';const edit=document.createElement('button');edit.className='button';edit.type='button';edit.textContent='تعديل';edit.addEventListener('click',()=>openForm(item));const del=document.createElement('button');del.className='button danger';del.type='button';del.textContent='حذف';del.addEventListener('click',()=>remove(item));actions.append(edit,del);row.append(info,actions);root.append(row)})}
function openForm(item=null){editingId=item?.id||null;$('form-title').textContent=editingId?`تعديل ${label}`:`إضافة ${label.slice(0,-1)}`;$('item-name').value=item?.name||'';$('item-description').value=item?.description||'';$('item-icon').value=item?.icon||'';$('item-order').value=Number.isFinite(Number(item?.order))?Number(item.order):0;$('item-active').checked=item?.active!==false;if($('item-stable'))$('item-stable').value=item?.stableId||'';if($('item-branches'))$('item-branches').value=Array.isArray(item?.branchIds)?item.branchIds.join(', '):'';if($('stable-wrap'))$('stable-wrap').hidden=collectionName!=='categories';if($('branches-wrap'))$('branches-wrap').hidden=collectionName!=='subjects';$('item-form').showModal();$('item-name').focus()}
function closeForm(){if($('item-form').open)$('item-form').close();editingId=null}
async function load(reset=true){const root=$('content-list');if(reset){state.cursor=null;rows=[]}root.replaceChildren(stateMessage('جاري التحميل...'));try{const page=await loadPage(collectionName,{});rows=reset?page.rows:[...rows,...page.rows];state.cursor=page.nextCursor;render();$('load-more')?.toggleAttribute('hidden',!page.hasMore)}catch(e){console.error('[admin/content-manager.load]',e);root.replaceChildren(stateMessage('تعذر تحميل البيانات.',true))}}
async function remove(item){if(!confirm(`تأكيد حذف «${item.name||''}»؟`))return;try{await removeAdminItem(collectionName,item.id);await load()}catch(e){console.error(e);alert('تعذر الحذف. قد تكون هناك علاقات مرتبطة بهذا العنصر.')}}
const requiredRole=collectionName==='branches'||collectionName==='categories'?ROLES.SUPERADMIN:ROLES.CONTENT_ADMIN;await requireAdmin(requiredRole);document.title=`إدارة ${label} | مِنهَاج`;$('page-title').textContent=`إدارة ${label}`;$('add-item').textContent=`إضافة ${label.slice(0,-1)}`;$('add-item').addEventListener('click',()=>openForm());$('cancel-form').addEventListener('click',closeForm);$('load-more')?.addEventListener('click',()=>load(false));$('item-form').addEventListener('submit',async event=>{event.preventDefault();const name=$('item-name').value.trim(),order=Number($('item-order').value);if(!name)return alert('الاسم مطلوب.');if(name.length>200)return alert('الاسم طويل جدًا.');if(!Number.isInteger(order)||order<0)return alert('الترتيب يجب أن يكون رقمًا صحيحًا موجبًا أو صفرًا.');const data={name,description:$('item-description').value.trim(),icon:$('item-icon').value.trim(),order,active:$('item-active').checked};if(collectionName==='categories'){data.stableId=$('item-stable').value.trim();if(!data.stableId)return alert('stableId مطلوب للتصنيف.')}if(collectionName==='subjects')data.branchIds=$('item-branches').value.split(',').map(v=>v.trim()).filter(Boolean);try{await saveAdminItem(collectionName,editingId,data);closeForm();await load()}catch(e){console.error(e);alert('تعذر الحفظ. تحقق من الصلاحيات والبيانات.')}});await load();
