import { db } from '../services/firebase.js';
import { collection, getDocs, query, limit, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { getAdmin } from './data.js';
import { classifyResource } from '../services/ai/aiService.js';
const FOLDER='application/vnd.google-apps.folder',DOC='application/vnd.google-apps.document',SHEET='application/vnd.google-apps.spreadsheet';
const MAX_FILES=2000,MAX_CONTENT=6000,AI_URL=String(window.MINHAJ_AI_URL||'').trim().replace(/\/$/,'');
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');let refs={branches:[],subjects:[],categories:[]},files=[];
const msg=(text,error=false)=>{const e=$('driveMsg');if(e){e.textContent=text;e.className=text?`message ${error?'error':'success'}`:'message'}};
async function getRef(name){return(await getDocs(query(collection(db,name),limit(500)))).docs.map(d=>({id:d.id,...d.data()}))}
async function loadRefs(){[refs.branches,refs.subjects,refs.categories]=await Promise.all(['branches','subjects','categories'].map(getRef))}
function parseDriveUrl(value){try{const u=new URL(String(value||'').trim());if(!/drive\.google\.com$/i.test(u.hostname))return null;let m=u.pathname.match(/\/file\/d\/([\w-]+)/);if(m)return{id:m[1],kind:'file'};m=u.pathname.match(/\/folders\/([\w-]+)/);if(m)return{id:m[1],kind:'folder'};const id=u.searchParams.get('id');return id?{id,kind:u.pathname.includes('folder')?'folder':'file'}:null}catch{return null}}
async function drive(path,params={}){if(!AI_URL)throw Error('مساعد منهاج غير مهيأ.');const u=new URL(`${AI_URL}/drive/${path}`);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error||`Drive API ${r.status}`);return d}
async function raw(path,params={}){try{const d=await drive(path,params);return typeof d==='string'?d:JSON.stringify(d).slice(0,MAX_CONTENT)}catch{return ''}}
async function readContent(x){try{if(x.mimeType===DOC)return(await raw(`files/${encodeURIComponent(x.id)}/export`,{mimeType:'text/plain'})).slice(0,MAX_CONTENT);if(x.mimeType===SHEET)return(await raw(`files/${encodeURIComponent(x.id)}/export`,{mimeType:'text/csv'})).slice(0,MAX_CONTENT);if(/^text\//i.test(x.mimeType||''))return(await raw(`files/${encodeURIComponent(x.id)}`,{alt:'media'})).slice(0,MAX_CONTENT);return ''}catch{return ''}}
async function inspect(value){const p=parseDriveUrl(value);if(!p)throw Error('رابط Google Drive غير صالح.');if(p.kind==='file'){const x=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,size,modifiedTime,webViewLink,description,trashed'});if(x.trashed)throw Error('العنصر موجود في سلة المهملات.');return[{...x,content:await readContent(x)}]}const root=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,trashed'});if(root.trashed)throw Error('المجلد موجود في سلة المهملات.');if(root.mimeType!==FOLDER)return[{...root,content:await readContent(root)}];const out=[];async function walk(parent,path,depth=0){if(depth>12||out.length>=MAX_FILES)return;let token='';do{const d=await drive('files',{q:`'${parent}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType,size,modifiedTime,webViewLink,description)',pageSize:'100',orderBy:'folder,name',...(token?{pageToken:token}:{})});for(const x of d.files||[]){if(x.mimeType===FOLDER)await walk(x.id,[...path,x.name],depth+1);else if(out.length<MAX_FILES)out.push({...x,path:[...path,x.name].join(' / ')})}token=d.nextPageToken||''}while(token&&out.length<MAX_FILES)}await walk(root.id,[root.name]);return Promise.all(out.map(async x=>({...x,content:await readContent(x)})))}
function resolve(v,rows){const s=String(v??'').trim();return rows.find(x=>String(x.id)===s)?.id||rows.find(x=>String(x.stableId||'')===s)?.id||rows.find(x=>String(x.name||'').toLowerCase()===s.toLowerCase())?.id||''}
function opts(rows,selected){return`<option value="">غير محدد</option>${rows.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(selected)?'selected':''}>${esc(x.name)}${x.active===false?' (غير نشط)':''}</option>`).join('')}`}
async function classifyFile(file){try{const r=await classifyResource({name:file.name,path:file.path||'',description:`${file.description||''}\n${(file.content||'').slice(0,1500)}`});const subject=refs.subjects.find(x=>String(x.name||'').trim()===String(r.subject||'').trim()||String(x.stableId||'')===String(r.subject||'').trim());const category=refs.categories.find(x=>String(x.name||'').trim()===String(r.category||'').trim()||String(x.stableId||'')===String(r.category||'').trim());const branch=refs.branches.find(x=>String(x.name||'').trim()===String(r.branch||'').trim()||String(x.stableId||'')===String(r.branch||'').trim());return{fileId:file.id,suggestedTitle:file.name,subjectId:subject?.id||'',categoryId:category?.id||'',branchIds:branch?.id?[branch.id]:[],confidence:Number(r?.confidence?.overall)||0,needsReview:r.needsReview!==false,reason:r.reason||'تحليل مساعد منهاج'}}catch{return{fileId:file.id,suggestedTitle:file.name,subjectId:'',categoryId:'',branchIds:[],confidence:0,needsReview:true,reason:'تعذر التحليل الآلي، راجع التصنيف يدويًا'}}}
function renderRows(results){const map=new Map(results.map(a=>[String(a.fileId),a]));$('driveResults').innerHTML=files.map((f,i)=>{const a=map.get(String(f.id))||{};return`<article class="drive-review-card"><label class="check"><input type="checkbox" data-drive-select="${i}" checked> ${esc(f.name)}</label><small>${esc(f.path||f.mimeType||'')}</small><label>العنوان<input data-drive-title="${i}" value="${esc(a.suggestedTitle||f.name)}"></label><label>المادة<select data-drive-subject="${i}">${opts(refs.subjects,a.subjectId)}</select></label><label>التصنيف<select data-drive-category="${i}">${opts(refs.categories,a.categoryId)}</select></label><div class="drive-branches"><strong>الفروع</strong>${refs.branches.map(b=>`<label class="check"><input type="checkbox" data-drive-branch="${i}" value="${esc(b.id)}" ${(a.branchIds||[]).map(String).includes(String(b.id))?'checked':''}> ${esc(b.name)}</label>`).join('')}</div><small>الثقة: ${Number(a.confidence)||0}% • ${esc(a.reason||'مراجعة يدوية')}</small></article>`}).join('')||'<div class="empty">لا توجد ملفات.</div>'}
async function addSelected(){const admin=getAdmin();if(!admin)throw Error('انتهت جلسة الإدارة.');const selected=[...document.querySelectorAll('[data-drive-select]:checked')].map(e=>Number(e.dataset.driveSelect));let added=0,skipped=0;for(const i of selected){const f=files[i],card=document.querySelector(`[data-drive-select="${i}"]`)?.closest('.drive-review-card');if(!f||!card)continue;const subjectId=resolve(card.querySelector('[data-drive-subject]')?.value,refs.subjects),categoryId=resolve(card.querySelector('[data-drive-category]')?.value,refs.categories),branchIds=[...card.querySelectorAll('[data-drive-branch]:checked')].map(e=>resolve(e.value,refs.branches)).filter(Boolean),title=card.querySelector('[data-drive-title]')?.value.trim()||f.name;if(!subjectId||!branchIds.length){skipped++;continue}await addDoc(collection(db,'sourceRegistry'),{sourceId:f.id,name:title,title,url:f.webViewLink||`https://drive.google.com/file/d/${f.id}/view`,originalTitle:f.name,path:f.path||'',mimeType:f.mimeType||'',branchIds,subjectId,categoryId,keywords:[],tags:[],status:'pending_review',needsReview:true,active:false,provider:'google_drive',createdBy:admin.uid||'',createdByEmail:admin.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});added++}msg(`تمت إضافة ${added} مصدر إلى سجل المراجعة${skipped?`، وتم تجاوز ${skipped} لبيانات ناقصة`:''}.`)}
export async function renderDrive(root){root.innerHTML=`<div class="section-head"><div><h2>مصادر Google Drive</h2><p class="muted">مفاتيح Google Drive وGemini لا تُحفظ في المتصفح. يتم تمرير الطلبات عبر Worker.</p></div></div><div class="form-card"><label>رابط ملف أو مجلد Google Drive<input id="driveUrl" type="url" placeholder="https://drive.google.com/drive/folders/..." autocomplete="off"></label><div class="actions"><button id="inspectDrive" class="button primary">فحص Drive وتصنيف</button></div><p id="driveMsg" class="message"></p></div><div id="driveResults" class="drive-items"></div><div class="form-card"><button id="addDriveSources" class="button primary">إضافة المحدد إلى المراجعة</button></div>`;await loadRefs();$('inspectDrive').onclick=async()=>{try{$('inspectDrive').disabled=true;msg('جاري فحص Drive...');files=await inspect($('driveUrl').value);msg(`تم العثور على ${files.length} ملف. جاري التصنيف...`);const results=[];for(let i=0;i<files.length;i++){results.push(await classifyFile(files[i]));if((i+1)%10===0)msg(`تم تصنيف ${i+1} من ${files.length}...`)}renderRows(results);msg('اكتمل التحليل. راجع البيانات ثم أضف المصادر.')}catch(e){console.error('[admin.drive]',e);msg(e?.message||'تعذر فحص Drive.',true)}finally{$('inspectDrive').disabled=false}};$('addDriveSources').onclick=async()=>{try{$('addDriveSources').disabled=true;await addSelected()}catch(e){console.error('[admin.drive.add]',e);msg(e?.message||'تعذر إضافة المصادر.',true)}finally{$('addDriveSources').disabled=false}}}
