import { db } from '../services/firebase.js';
import { collection, addDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { getAdmin } from './data.js';
import { getPage } from '../repositories/resourceRepository.js';
import { getCurrentIdToken } from '../services/firebase/auth.js';

const FOLDER='application/vnd.google-apps.folder',DOC='application/vnd.google-apps.document',SHEET='application/vnd.google-apps.spreadsheet';
const CONTENT_LIMIT=12000,WORKER=window.MINHAJ_AI_URL||'', $=id=>document.getElementById(id);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let refs={branches:[],subjects:[],categories:[]},files=[];
const msg=(text,error=false)=>{const e=$('driveMsg');if(e){e.textContent=text;e.className=text?`message ${error?'error':'success'}`:'message'}};
async function relationRows(name){const rows=[];let cursor=null;while(rows.length<500){const r=await getPage(name,{orderField:'order'},100,cursor);rows.push(...r.rows);if(!r.hasMore||!r.nextCursor)break;cursor=r.nextCursor}return rows}
async function loadRefs(){[refs.branches,refs.subjects,refs.categories]=await Promise.all(['branches','subjects','categories'].map(relationRows))}
async function worker(path,body){if(!WORKER)throw Error('خدمة Cloudflare Worker غير مهيأة.');const token=await getCurrentIdToken();if(!token)throw Error('انتهت جلسة الإدارة.');const r=await fetch(`${WORKER}${path}`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d?.error||`Worker HTTP ${r.status}`);return d}
function parseDriveUrl(value){try{const u=new URL(String(value||'').trim());if(!/drive\.google\.com$/i.test(u.hostname))return null;let m=u.pathname.match(/\/file\/d\/([\w-]+)/);if(m)return{id:m[1],kind:'file'};m=u.pathname.match(/\/folders\/([\w-]+)/);if(m)return{id:m[1],kind:'folder'};const id=u.searchParams.get('id');return id?{id,kind:u.pathname.includes('folder')?'folder':'file'}:null}catch{return null}}
async function drive(path,params={}){const d=await worker('/drive',{path,params});return d.data}
async function raw(path,params={}){try{return String((await drive(path,{...params,alt:'media'}))||'').slice(0,CONTENT_LIMIT)}catch{return ''}}
async function readContent(x){try{if(x.mimeType===DOC)return raw(`files/${encodeURIComponent(x.id)}/export`,{mimeType:'text/plain'});if(x.mimeType===SHEET)return raw(`files/${encodeURIComponent(x.id)}/export`,{mimeType:'text/csv'});if(/^text\//i.test(x.mimeType||''))return raw(`files/${encodeURIComponent(x.id)}`,{alt:'media'});return ''}catch{return ''}}
async function inspect(value){const p=parseDriveUrl(value);if(!p)throw Error('رابط Google Drive غير صالح.');if(p.kind==='file'){const x=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,size,modifiedTime,webViewLink,description,trashed'});if(x.trashed)throw Error('العنصر موجود في سلة المهملات.');return [{...x,content:await readContent(x)}]}const root=await drive(`files/${encodeURIComponent(p.id)}`,{fields:'id,name,mimeType,trashed'});if(root.trashed)throw Error('المجلد موجود في سلة المهملات.');if(root.mimeType!==FOLDER)return [{...root,content:await readContent(root)}];const out=[];async function walk(parent,path,depth=0){if(depth>12||out.length>=2000)return;let token='';do{const d=await drive('files',{q:`'${parent}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType,size,modifiedTime,webViewLink,description)',pageSize:'1000',orderBy:'folder,name',...(token?{pageToken:token}:{})});for(const x of d.files||[]){if(x.mimeType===FOLDER)await walk(x.id,[...path,x.name],depth+1);else out.push({...x,path:[...path,x.name].join(' / ')})}token=d.nextPageToken||''}while(token&&out.length<2000)}await walk(root.id,[root.name]);return (await Promise.allSettled(out.map(readContent))).map((r,i)=>({...out[i],content:r.status==='fulfilled'?r.value:''}))}
function norm(s){return String(s??'').toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}]+/gu,' ').trim()}
function score(text,row){const name=norm(row?.name);if(!name)return 0;const t=norm(text);if(t.includes(name))return 1;const words=name.split(' ').filter(w=>w.length>1);return words.length?words.filter(w=>t.includes(w)).length/words.length:0}
function resolve(v,rows){const s=String(v??'').trim();return rows.find(x=>String(x.id)===s)?.id||rows.find(x=>String(x.stableId||'')===s)?.id||rows.find(x=>norm(x.name)===norm(s))?.id||''}
function complete(a,item){let subjectId=resolve(a?.subjectId,refs.subjects),categoryId=resolve(a?.categoryId,refs.categories),branchIds=[...(a?.branchIds||[])].map(v=>resolve(v,refs.branches)).filter(Boolean);const hay=`${item.name||''} ${item.path||''} ${item.description||''} ${item.content||''}`;if(!subjectId&&categoryId){const c=refs.categories.find(x=>x.id===categoryId);subjectId=resolve(c?.subjectId,refs.subjects)}if(!subjectId){const best=refs.subjects.map(s=>({s,n:score(hay,s)})).sort((a,b)=>b.n-a.n)[0];if(best&&best.n>=.34)subjectId=best.s.id}if(!branchIds.length&&subjectId){const s=refs.subjects.find(x=>x.id===subjectId);branchIds=(s?.branchIds||[]).map(v=>resolve(v,refs.branches)).filter(Boolean)}if(!branchIds.length&&categoryId){const c=refs.categories.find(x=>x.id===categoryId);branchIds=(c?.branchIds||[]).map(v=>resolve(v,refs.branches)).filter(Boolean)}if(!branchIds.length){const ranked=refs.branches.map(b=>({b,n:score(hay,b)})).sort((a,b)=>b.n-a.n)[0];if(ranked?.n>=.34)branchIds=[ranked.b.id]}if(!branchIds.length&&refs.branches.length===1)branchIds=[refs.branches[0].id];return{...a,fileId:item.id,subjectId,categoryId,branchIds,suggestedTitle:a?.suggestedTitle||item.name||'مصدر Drive'}}
function fallback(items,reason){return items.map(x=>{const s=refs.subjects.map(v=>({v,n:score(`${x.name} ${x.path} ${x.description} ${x.content}`,v)})).sort((a,b)=>b.n-a.n)[0];const c=refs.categories.map(v=>({v,n:score(`${x.name} ${x.path} ${x.description} ${x.content}`,v)})).sort((a,b)=>b.n-a.n)[0];return complete({subjectId:s?.n>=.34?s.v.id:'',categoryId:c?.n>=.34?c.v.id:'',branchIds:[],confidence:Math.round(Math.max(s?.n||0,c?.n||0)*100),needsReview:true,reason},x)})}
async function gemini(items){try{const d=await worker('/ai',{action:'drive_classify',branches:JSON.stringify(refs.branches.map(x=>({id:x.id,name:x.name,stableId:x.stableId||''}))),subjects:JSON.stringify(refs.subjects.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',branchIds:x.branchIds||[]}))),categories:JSON.stringify(refs.categories.map(x=>({id:x.id,name:x.name,stableId:x.stableId||'',subjectId:x.subjectId||'',branchIds:x.branchIds||[]}))),items:JSON.stringify(items.map(x=>({fileId:x.id,name:x.name,path:x.path||'',description:x.description||'',content:(x.content||'').slice(0,CONTENT_LIMIT)})))});return(Array.isArray(d.result)?d.result:[]).map(a=>complete(a,items.find(x=>String(x.id)===String(a.fileId))||{}))}catch(e){console.warn('[admin.drive] classification fallback',e);return fallback(items,e.message||'تعذر التحليل')}}
function opts(rows,selected){return `<option value="">غير محدد</option>${rows.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(selected)?'selected':''}>${esc(x.name)}${x.active===false?' (غير نشط)':''}</option>`).join('')}`}
function renderRows(results){const map=new Map(results.map(a=>[String(a.fileId),a]));$('driveResults').innerHTML=files.map((f,i)=>{const a=complete(map.get(String(f.id))||{},f);return `<article class="drive-review-card"><label class="check"><input type="checkbox" data-drive-select="${i}" checked> ${esc(f.name)}</label><small>${esc(f.path||f.mimeType||'')}</small><label>العنوان<input data-drive-title="${i}" value="${esc(a.suggestedTitle)}"></label><label>المادة<select data-drive-subject="${i}">${opts(refs.subjects,a.subjectId)}</select></label><label>التصنيف<select data-drive-category="${i}">${opts(refs.categories,a.categoryId)}</select></label><div class="drive-branches"><strong>الفروع</strong>${refs.branches.map(b=>`<label class="check"><input type="checkbox" data-drive-branch="${i}" value="${esc(b.id)}" ${(a.branchIds||[]).map(String).includes(String(b.id))?'checked':''}> ${esc(b.name)}</label>`).join('')}</div><small>الثقة: ${Number(a.confidence)||0}% • ${esc(a.reason||'تحليل')}</small></article>`}).join('')||'<div class="empty">لا توجد ملفات.</div>'}
async function addSelected(){const admin=getAdmin();if(!admin)throw Error('انتهت جلسة الإدارة.');const selected=[...document.querySelectorAll('[data-drive-select]:checked')].map(e=>Number(e.dataset.driveSelect));let added=0,skipped=0;for(const i of selected){const f=files[i];if(!f)continue;const card=document.querySelector(`[data-drive-select="${i}"]`)?.closest('.drive-review-card');const subjectId=resolve(card?.querySelector('[data-drive-subject]')?.value,refs.subjects),categoryId=resolve(card?.querySelector('[data-drive-category]')?.value,refs.categories),branchIds=[...card?.querySelectorAll('[data-drive-branch]:checked')||[]].map(e=>resolve(e.value,refs.branches)).filter(Boolean),title=card?.querySelector('[data-drive-title]')?.value.trim()||f.name;const inferred=complete({},f);const finalSubjectId=subjectId||inferred.subjectId;const finalBranchIds=branchIds.length?branchIds:inferred.branchIds;if(!finalSubjectId||!finalBranchIds.length){skipped++;continue}await addDoc(collection(db,'sourceRegistry'),{sourceId:f.id,name:title,title,url:f.webViewLink||`https://drive.google.com/file/d/${f.id}/view`,originalTitle:f.name,path:f.path||'',mimeType:f.mimeType||'',branchIds:finalBranchIds,subjectId:finalSubjectId,categoryId,keywords:[],tags:[],status:'pending_review',needsReview:true,active:false,provider:'google_drive',createdBy:admin.uid||'',createdByEmail:admin.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});added++}msg(`تمت إضافة ${added} مصدر إلى سجل المراجعة${skipped?`، وتم تجاوز ${skipped} بعد تعذر تحديد المادة أو الفرع`:''}.`)}
export async function renderDrive(root){root.innerHTML=`<div class="section-head"><div><h2>مصادر Google Drive</h2><p class="muted">مفاتيح Google Drive وGemini محفوظة على Cloudflare Worker ولا تُخزن في المتصفح.</p></div></div><div class="form-card"><label>رابط ملف أو مجلد Google Drive<input id="driveUrl" type="url" placeholder="https://drive.google.com/drive/folders/..." autocomplete="off"></label><div class="actions"><button id="inspectDrive" class="button primary">فحص Drive وتصنيف</button></div><p id="driveMsg" class="message"></p></div><div id="driveResults" class="drive-items"></div><div class="form-card"><button id="addDriveSources" class="button primary">إضافة المحدد إلى المراجعة</button></div>`;await loadRefs();$('inspectDrive').onclick=async()=>{try{$('inspectDrive').disabled=true;msg('جاري فحص Drive...');files=await inspect($('driveUrl').value);msg(`تم العثور على ${files.length} ملف. جاري التصنيف...`);const r=await gemini(files);renderRows(r);msg('اكتمل التحليل. راجع المادة والفروع ثم أضف المصادر.')}catch(e){console.error('[admin.drive]',e);msg(e?.message||'تعذر تحميل مصادر Google Drive.',true)}finally{$('inspectDrive').disabled=false}};$('addDriveSources').onclick=()=>addSelected().catch(e=>msg(e?.message||'تعذر الإضافة.',true))}
