import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, serverTimestamp, query, where, limit } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { db } from '../services/firebase.js';
import { requireAdmin, ROLES } from '../services/firebase/adminCore.js';
import { renderNavbar, renderFooter } from '../components/layout.js';
import { escapeHtml, setBusy } from '../core/utils.js';
import { writeAdminLog } from '../services/firebase/adminLogRepository.js';
import { getPage } from '../repositories/resourceRepository.js';
await requireAdmin(ROLES.CONTENT_ADMIN);renderNavbar();renderFooter();const $=id=>document.getElementById(id);let schools=[],directorates=[],schoolCursor=null;
const clean=v=>String(v??'').trim(),norm=v=>clean(v).toLocaleLowerCase('ar');
function errorText(e){const key=e?.message||e?.code||'';return({SCHOOL_NAME_REQUIRED:'اسم المدرسة مطلوب',SCHOOL_CODE_REQUIRED:'رقم / كود المدرسة مطلوب',SCHOOL_DIRECTORATE_REQUIRED:'اختر المديرية',SCHOOL_DUPLICATE_CODE:'رقم / كود المدرسة مستخدم مسبقًا',PERMISSION_DENIED:'ليس لديك صلاحية'}[key]||'تعذر تنفيذ العملية.').toString()}
async function loadDirectorates(){directorates=[];let cursor=null;while(directorates.length<500){const r=await getPage('directorates',{orderField:'name'},100,cursor);directorates.push(...r.rows);if(!r.hasMore||!r.nextCursor)break;cursor=r.nextCursor}directorates.sort((a,b)=>norm(a.name).localeCompare(norm(b.name),'ar'));fillDirectorates()}
async function loadData(reset=true){const root=$('school-list');if(reset){schools=[];schoolCursor=null;root.innerHTML='<div class="loading">جاري تحميل المدارس...</div>';await loadDirectorates()}const q=norm($('school-search').value),did=$('school-directorate').value,gov=$('school-governorate').value;const result=await getPage('schools',{search:q,searchField:'name',orderField:'name',directorateId:did||undefined,governorateName:gov||undefined},20,schoolCursor);schools=reset?result.rows:[...schools,...result.rows];schoolCursor=result.nextCursor;render();let more=$('school-more');if(!more){more=document.createElement('button');more.id='school-more';more.className='button';more.textContent='تحميل المزيد';root.parentElement.append(more);more.onclick=()=>loadData(false)}more.hidden=!result.hasMore}
function fillDirectorates(){const filter=$('school-directorate'),form=$('school-directorate-id');filter.innerHTML='<option value="">كل المديريات</option>';form.innerHTML='<option value="">اختر المديرية</option>';directorates.forEach(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=d.name;filter.append(o);form.append(o.cloneNode(true))});const gs=[...new Map(directorates.filter(d=>d.governorate).map(d=>[norm(d.governorate),d.governorate])).values()].sort((a,b)=>norm(a).localeCompare(norm(b),'ar'));const g=$('school-governorate');g.innerHTML='<option value="">كل المحافظات</option>';gs.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;g.append(o)})}
function syncDirectorate(){const d=directorates.find(x=>x.id===$('school-directorate-id').value);if(!d)return;$('school-directorate-name').value=d.name||'';$('school-governorate-name').value=d.governorate||'';$('school-area').value=d.area||''}
function resetForm(){['school-id','school-name','school-code','school-directorate-name','school-governorate-name','school-area','school-stages','school-manager','school-phone','school-email','school-address','school-notes'].forEach(id=>$(id).value='');$('school-directorate-id').value='';$('school-type').value='حكومية';$('school-gender').value='ذكور';$('school-active').checked=true;$('school-error').textContent='';$('school-form-title').textContent='إضافة مدرسة'}
function openForm(item=null){resetForm();if(item){$('school-id').value=item.id;['name','code','directorate-name','governorate-name','area','stages','manager','phone','email','address','notes'].forEach(k=>$('school-'+k).value=item[k]||'');$('school-directorate-id').value=item.directorateId||'';$('school-type').value=item.type||'حكومية';$('school-gender').value=item.gender||'ذكور';$('school-active').checked=item.active!==false;$('school-form-title').textContent='تعديل المدرسة'}syncDirectorate();$('school-modal').showModal();$('school-name').focus()}
function closeForm(){if($('school-modal').open)$('school-modal').close()}
function render(){const q=norm($('school-search').value),did=$('school-directorate').value,gov=$('school-governorate').value,root=$('school-list');root.replaceChildren();const filtered=schools.filter(x=>{const d=directorates.find(z=>z.id===x.directorateId),dn=d?.name||x.directorateName,gn=d?.governorate||x.governorateName,area=d?.area||x.area;return(!did||x.directorateId===did)&&(!gov||gn===gov)&&(!q||[x.name,x.code,x.manager,dn,gn,area].some(v=>norm(v).includes(q)))}).sort((a,b)=>norm(a.name).localeCompare(norm(b.name),'ar'));if(!filtered.length){root.innerHTML='<div class="empty">لا توجد مدارس مطابقة.</div>';return}for(const x of filtered){const d=directorates.find(z=>z.id===x.directorateId),dn=d?.name||x.directorateName||'غير محددة',gn=d?.governorate||x.governorateName||'',area=d?.area||x.area||'';const row=document.createElement('article');row.className='card admin-row';const info=document.createElement('div');info.innerHTML=`<b>${escapeHtml(x.name||'بدون اسم')}</b><small><strong>رقم المدرسة:</strong> ${escapeHtml(x.code||'غير محدد')} • ${escapeHtml(x.type||'')} • ${escapeHtml(x.gender||'')}</small><small><strong>المديرية:</strong> ${escapeHtml(dn)} • <strong>المحافظة:</strong> ${escapeHtml(gn)} • <strong>المنطقة:</strong> ${escapeHtml(area)}</small><small>${escapeHtml(x.manager?`المدير: ${x.manager}`:'لم يحدد مدير المدرسة')} ${x.active===false?'• غير نشطة':'• نشطة'}</small>`;const actions=document.createElement('div');actions.className='row-actions';const edit=document.createElement('button');edit.className='button';edit.type='button';edit.textContent='تعديل';edit.onclick=()=>openForm(x);const del=document.createElement('button');del.className='button danger';del.type='button';del.textContent='حذف';del.onclick=()=>remove(x);actions.append(edit,del);row.append(info,actions)}}
async function remove(item){if(!confirm(`حذف مدرسة «${item.name||''}»؟`))return;try{await deleteDoc(doc(db,'schools',item.id));try{await writeAdminLog({action:'delete',collectionName:'schools',targetId:item.id,details:{name:item.name,code:item.code}})}catch(e){console.warn('[schools.log]',e)}await loadData()}catch(e){console.error('[schools.delete]',e);alert(errorText(e))}}
$('add-school').onclick=()=>openForm();$('close-school').onclick=closeForm;$('cancel-school').onclick=closeForm;$('school-directorate-id').onchange=syncDirectorate;$('school-search').oninput=()=>loadData();$('school-directorate').onchange=()=>loadData();$('school-governorate').onchange=()=>loadData();
$('school-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;setBusy(button,true,'جاري الحفظ...');$('school-error').textContent='';try{const id=clean($('school-id').value)||null,name=clean($('school-name').value),code=clean($('school-code').value),directorateId=$('school-directorate-id').value,d=directorates.find(x=>x.id===directorateId);if(!name)throw new Error('SCHOOL_NAME_REQUIRED');if(!code)throw new Error('SCHOOL_CODE_REQUIRED');if(!d)throw new Error('SCHOOL_DIRECTORATE_REQUIRED');const duplicate=await getDocs(query(collection(db,'schools'),where('code','==',code),limit(2)));if(duplicate.docs.some(x=>x.id!==id))throw new Error('SCHOOL_DUPLICATE_CODE');const data={name,code,directorateId,directorateName:d.name||'',governorateName:d.governorate||'',area:d.area||'',type:$('school-type').value,gender:$('school-gender').value,stages:clean($('school-stages').value),manager:clean($('school-manager').value),phone:clean($('school-phone').value),email:clean($('school-email').value),address:clean($('school-address').value),notes:clean($('school-notes').value),active:$('school-active').checked};if(id){await updateDoc(doc(db,'schools',id),{...data,updatedAt:serverTimestamp()});try{await writeAdminLog({action:'update',collectionName:'schools',targetId:id,details:{name,code}})}catch(e){console.warn('[schools.log]',e)}}else{const result=await addDoc(collection(db,'schools'),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});try{await writeAdminLog({action:'create',collectionName:'schools',targetId:result.id,details:{name,code}})}catch(e){console.warn('[schools.log]',e)}}closeForm();await loadData()}catch(err){console.error('[schools.save]',err);$('school-error').textContent=errorText(err)}finally{setBusy(button,false)}};
loadData().catch(e=>{$('school-list').innerHTML=`<div class="error-box">${escapeHtml(errorText(e))}</div>`});
